#INCLUDE 'PROTHEUS.ch'
#INCLUDE 'PARMTYPE.ch'

USER FUNCTION ADEST023P()

	Local cRet

	U_ADINF009P(SUBSTRING(ALLTRIM(PROCNAME()),3,LEN(ALLTRIM(PROCNAME()))) + '.PRW',SUBSTRING(ALLTRIM(PROCNAME()),3,LEN(ALLTRIM(PROCNAME()))),'')
	
	cRet := IIF(CFILANT=="02",Posicione("SBE",10,xFilial("SBE")+SB1->B1_COD+IIF(!RetArqProd(SB1->B1_COD),POSICIONE("SBZ",1,xFilial("SBZ")+SB1->B1_COD,"BZ_LOCPAD"),POSICIONE("SB1",1,xFilial("SB1")+SB1->B1_COD,"B1_LOCPAD")) ,"BE_LOCALIZ"),SB1->B1_ENDALM2)  
	
RETURN(cRet)