/*/{Protheus.doc} User Function ADFIN131P
    Rotina de processamento do CISP.
    @type  Function
    @author Leonardo P. Monteiro
    @since 23/02/2022
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    @history chamado TI - Leonardo P. Monteiro - 23/02/2022 - Fonte em desenvolvimento.
    /*/
User Function ADFIN131P()

Return return_var
